name: 'Deploy SOAT Database Infra'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SECRET_NAME: "soat/db/database_url"

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      
      - name: Get Terraform Outputs and Save to Secrets Manager
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          DB_HOSTNAME=$(terraform output -raw db_hostname)
          DB_PORT=$(terraform output -raw db_port)
          DB_USERNAME=$(terraform output -raw db_username)
          DB_PASSWORD=$(terraform output -raw db_password)
          DB_NAME=$(terraform output -raw db_name_output)
          
          DATABASE_URL="postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}"
          
          aws secretsmanager put-secret-value --secret-id ${{ env.SECRET_NAME }} --secret-string "$DATABASE_URL"
