name: 'Deploy SOAT Database Infra'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DB_SECRET_NAME: "soat/infra/dbs"

permissions:
  id-token: write
  contents: read

jobs:
  test-and-analyze:
    name: 'Test and Analyze'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          check: CKV_AWS_118,CKV_AWS_16
          soft_fail: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        with:
          args: >
            -Dsonar.verbose=true

      - name: SonarCloud Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Test
        run: terraform test
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_mongo_username: ${{ secrets.TF_VAR_MONGO_USERNAME }}
          TF_VAR_mongo_password: ${{ secrets.TF_VAR_mongo_password }}

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_mongo_username: ${{ secrets.TF_VAR_MONGO_USERNAME }}
          TF_VAR_mongo_password: ${{ secrets.TF_VAR_MONGO_PASSWORD }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false    
        env:
          TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
          TF_VAR_mongo_username: ${{ secrets.TF_VAR_MONGO_USERNAME }}
          TF_VAR_mongo_password: ${{ secrets.TF_VAR_mongo_password }}
      
      - name: Get Terraform Outputs and Save to Secrets Manager
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          upsert_secret() {
            local secret_id=$1
            local secret_value=$2
            
            echo "A processar segredo: $secret_id"
            
            if aws secretsmanager describe-secret --secret-id "$secret_id" > /dev/null 2>&1; then
              echo "Segredo existe. A atualizar valor..."
              aws secretsmanager put-secret-value --secret-id "$secret_id" --secret-string "$secret_value"
            else
              echo "Segredo não existe. A criar novo..."
              aws secretsmanager create-secret --name "$secret_id" --secret-string "$secret_value" --description "Gerado automaticamente pelo pipeline infra-db"
            fi
          }
        
          DB_HOSTNAME=$(terraform output -raw db_hostname)
          DB_PORT=$(terraform output -raw db_port)
          DB_USERNAME=$(terraform output -raw db_username)
          DB_PASSWORD=$(terraform output -raw db_password)
          DB_NAME=$(terraform output -raw db_name_output)
          DATABASE_URL="postgresql://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}"

          REDIS_HOSTNAME=$(terraform output -raw redis_endpoint)
          REDIS_URL="redis://${REDIS_HOSTNAME}:6379"

          MONGO_HOSTNAME=$(terraform output -raw mongo_endpoint)
          MONGO_USER=$(terraform output -raw mongodb_username)
          MONGO_PASS="$TF_VAR_mongo_password"
          MONGODB_URL="mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOSTNAME}:27017/?tls=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false"

          upsert_secret "soat/db/database_url" "$DATABASE_URL"

          upsert_secret "soat/db/database_url" "$DATABASE_URL"
          upsert_secret "soat/db/redis_url" "$REDIS_URL"
          upsert_secret "soat/db/mongodb_url" "$MONGODB_URL"
